kind: Service
apiVersion: v1
metadata:
  name: crud-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: crudapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deploy
  namespace: production
spec:
  selector:
    matchLabels:
      app: crudapp
  replicas: 2
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
      - name: php-crud
        image: farman17/dekkeng-crud:tag
        ports:
          - containerPort: 80
        env:
        - name: DB_HOST
          value: "dbsosmedia.cjorhe5jzkni.us-east-2.rds.amazonaws.com"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_PASS

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crud-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sosialmedia.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: crud-service
          servicePort: 80
