kind: Service
apiVersion: v1
metadata:
  name: crud-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: crudaps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deployment
  namespace: production
spec:
  selector:
    matchLabels:
      app: crudaps
  replicas: 2
  template:
    metadata:
      labels:
        app: crudaps
    spec:
      containers:
      - name: php-crudy
        image: farman17/crudzy:6.0
        ports:
          - containerPort: 80
        

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crud-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: crud.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: crud-service
          servicePort: 80
